tools: rename .resigned.apk to .signed.apk test output files
The input file is not signed, so it's not a resigning:

apksigner verify signer/apk/aligned-two-files.apk
DOES NOT VERIFY
ERROR: Missing META-INF/MANIFEST.MF